import { useEffect, useState } from 'react'
import type { RequestEvent } from '../types'
import { fetchRequestLedger, money } from '../lib/api'

export default function ActivityPanel({ token, tenantId }: { token: string; tenantId: string }) {
  const [events,setEvents]=useState<RequestEvent[]>([]),[cursor,setCursor]=useState<number|null>(null),[loading,setLoading]=useState(true),[filter,setFilter]=useState('all')
  const load=async(more=false)=>{setLoading(true);try{const page=await fetchRequestLedger(token,tenantId,more?cursor:null);setEvents(old=>more?[...old,...page.items]:page.items);setCursor(page.next_cursor)}finally{setLoading(false)}}
  useEffect(()=>{setEvents([]);setCursor(null);void load()},[tenantId])
  const visible=events.filter(e=>filter==='all'||(filter==='hit')===e.cached)
  const exportCsv=()=>{const rows=[['Time','Provider','Cache','Latency ms','Baseline cost','Actual cost','Saved'],...visible.map(e=>[e.created_at||'',e.provider,e.cached?'Hit':'Miss',String(e.latency_ms),String(e.baseline_cost),String(e.actual_cost),String(e.saved)])];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`promptcache-${tenantId}-requests.csv`;a.click();URL.revokeObjectURL(a.href)}
  return <article className='panel activity-panel'><div className='panel-head'><div><h2>Request savings ledger</h2><p>Auditable cost and performance for every gateway request.</p></div><div className='ledger-actions'><select value={filter} onChange={e=>setFilter(e.target.value)}><option value='all'>All requests</option><option value='hit'>Cache hits</option><option value='miss'>Cache misses</option></select><button onClick={exportCsv} disabled={!visible.length}>Export CSV</button></div></div>{visible.length?<div className='ledger-wrap'><div className='ledger-row ledger-head'><span>Request</span><span>Provider</span><span>Cache</span><span>Latency</span><span>Actual cost</span><span>Saved</span></div>{visible.map(e=><div className='ledger-row' key={e.id}><span><b>#{e.id}</b><small>{e.created_at?new Date(e.created_at).toLocaleString():'—'}</small></span><span>{e.provider}</span><span><i className={e.cached?'hit':'miss'}/>{e.cached?'Hit':'Miss'}</span><span>{e.latency_ms.toLocaleString()} ms</span><span>{money(e.actual_cost)}</span><span className='positive'>{e.saved>0?'+':''}{money(e.saved)}</span></div>)}</div>:<div className='app-empty'><b>{loading?'Loading requests…':'No matching requests'}</b><span>Gateway activity appears here automatically.</span></div>}{cursor&&<button className='load-more' onClick={()=>void load(true)} disabled={loading}>{loading?'Loading…':'Load more'}</button>}</article>
}
