import { useEffect, useState } from 'react'
import type { AlertSettings, Notification } from '../types'
import { fetchAlertSettings, fetchNotifications, markNotificationRead, saveAlertSettings } from '../lib/api'

export default function AlertPanel({token,tenantId}:{token:string;tenantId:string}){
 const [settings,setSettings]=useState<AlertSettings|null>(null),[notifications,setNotifications]=useState<Notification[]>([]),[webhook,setWebhook]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const load=async()=>{try{const [next,feed]=await Promise.all([fetchAlertSettings(token,tenantId),fetchNotifications(token,tenantId)]);setSettings(next);setNotifications(feed)}catch(e){setMessage(e instanceof Error?e.message:'Unable to load alerts')}}
 useEffect(()=>{setSettings(null);setNotifications([]);setMessage('');void load()},[token,tenantId])
 if(!settings)return <article className='panel alert-panel'><h2>Alerts & notifications</h2><p>{message||'Loading alerts…'}</p></article>
 const update=(key:keyof AlertSettings,value:number|boolean)=>setSettings({...settings,[key]:value})
 const save=async()=>{setSaving(true);setMessage('');try{const next=await saveAlertSettings(token,tenantId,{...settings,webhook_url:webhook||undefined});setSettings(next);setWebhook('');setMessage('Alert settings saved.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save alerts')}finally{setSaving(false)}}
 const read=async(id:number)=>{try{await markNotificationRead(token,tenantId,id);setNotifications(notifications.map(item=>item.id===id?{...item,read:true}:item))}catch(e){setMessage(e instanceof Error?e.message:'Unable to update notification')}}
 const unread=notifications.filter(item=>!item.read).length
 return <article className='panel alert-panel'><div className='panel-head'><div><h2>Alerts & notifications</h2><p>Get a heads-up before budget, performance, or cache efficiency needs attention.</p></div><span className='notice-pill'>{unread?`${unread} unread`:'All caught up'}</span></div><label className='alert-switch'><input type='checkbox' checked={settings.enabled} onChange={e=>update('enabled',e.target.checked)}/><span><b>Proactive workspace alerts</b><small>Create in-app notices and optional webhook messages.</small></span></label><div className='alert-fields'><label>Budget threshold<input type='number' min='1' max='100' value={settings.budget_percent} onChange={e=>update('budget_percent',Number(e.target.value))}/><small>% of monthly budget used</small></label><label>Latency threshold<input type='number' min='100' max='300000' value={settings.latency_ms} onChange={e=>update('latency_ms',Number(e.target.value))}/><small>milliseconds per request</small></label><label>Cache hit floor<input type='number' min='0' max='100' value={settings.cache_hit_percent} onChange={e=>update('cache_hit_percent',Number(e.target.value))}/><small>alert after 10 recent requests</small></label><label>HTTPS webhook <input type='url' value={webhook} onChange={e=>setWebhook(e.target.value)} placeholder={settings.webhook_configured?'Configured — enter to replace':'https://hooks.example.com/…'}/><small>{settings.webhook_configured?'A webhook is configured. Leave blank to keep it.':'Optional: compatible with Slack-style webhooks.'}</small></label></div>{message&&<p className='reliability-message'>{message}</p>}<div className='alert-footer'><p>Notifications are grouped by type and sent at most once per hour.</p><button onClick={()=>void save()} disabled={saving}>{saving?'Saving…':'Save alerts'}</button></div><div className='notification-feed'><div><h3>Recent notifications</h3><button onClick={()=>void load()}>Refresh</button></div>{notifications.length?notifications.map(item=><section className={item.read?'notification read':'notification'} key={item.id}><i className={item.severity}>{item.kind==='budget'?'$':item.kind==='latency'?'↯':'◌'}</i><div><b>{item.title}</b><p>{item.message}</p><small>{item.created_at?new Date(item.created_at).toLocaleString():'Just now'}</small></div>{!item.read&&<button onClick={()=>void read(item.id)}>Mark read</button>}</section>):<p className='feed-empty'>No alerts yet. Your activity will appear here when a threshold is reached.</p>}</div></article>
}
