import { useEffect, useState } from 'react'
import type { ProviderConnection } from '../types'
import { fetchBaseline, fetchWorkspaceProviders, setBaseline } from '../lib/api'

export default function BaselinePanel({token,tenantId}:{token:string;tenantId:string}){
 const [providers,setProviders]=useState<ProviderConnection[]>([]),[selected,setSelected]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{setMessage('');void Promise.all([fetchWorkspaceProviders(token,tenantId),fetchBaseline(token,tenantId)]).then(([items,baseline])=>{setProviders(items);setSelected(baseline.baseline_provider||items[0]?.name||'')}).catch(e=>setMessage(e instanceof Error?e.message:'Unable to load savings baseline'))},[token,tenantId])
 const save=async()=>{if(!selected)return;setSaving(true);setMessage('');try{await setBaseline(token,tenantId,selected);setMessage('Savings baseline updated. New requests will use it for comparisons.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to update savings baseline')}finally{setSaving(false)}}
 return <article className='panel baseline-panel'><div className='panel-head'><div><h2>Savings baseline</h2><p>Choose the provider PromptCache should compare against when calculating your cost savings.</p></div><span className='baseline-pill'>ROI control</span></div>{providers.length?<><label>REFERENCE PROVIDER<select value={selected} onChange={e=>setSelected(e.target.value)}>{providers.map(provider=><option key={provider.id} value={provider.name}>{provider.name} · {provider.model}</option>)}</select></label><p className='baseline-hint'>Pick the provider you would normally use without routing or caching. This affects future savings calculations, not your request routing.</p>{message&&<p className='reliability-message'>{message}</p>}<div className='baseline-footer'><span>Use a realistic default to keep ROI reporting trustworthy.</span><button onClick={()=>void save()} disabled={saving||!selected}>{saving?'Saving…':'Save baseline'}</button></div></>:<div className='app-empty'><b>Connect a provider first</b><span>Once a provider is connected, you can set the savings comparison baseline.</span></div>}</article>
}
