import { useEffect, useState } from 'react'
import type { ProviderConnection, ProviderPreset } from '../types'
import { connectProvider, disconnectProvider, fetchProviderPresets, fetchWorkspaceProviders, sendTestRequest, testProvider } from '../lib/api'

export default function ProviderOnboarding({token,tenantId,apiKey}:{token:string;tenantId:string;apiKey:string|null}){
 const [presets,setPresets]=useState<ProviderPreset[]>([]),[connections,setConnections]=useState<ProviderConnection[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
 const [type,setType]=useState('openai'),[secret,setSecret]=useState(''),[url,setUrl]=useState(''),[model,setModel]=useState(''),[input,setInput]=useState('0'),[output,setOutput]=useState('0')
 const load=()=>fetchWorkspaceProviders(token,tenantId).then(setConnections)
 useEffect(()=>{void Promise.all([fetchProviderPresets().then(setPresets),load()])},[tenantId])
 const preset=presets.find(p=>p.id===type),payload={provider_type:type,api_key:secret,base_url:url||preset?.base_url,model:model||preset?.model,input_cost_per_million:Number(input)||0,output_cost_per_million:Number(output)||0}
 const test=async()=>{setBusy('test');setMessage('');try{await testProvider(token,tenantId,payload);setMessage('Connection successful — credentials are valid.')}catch(e){setMessage(e instanceof Error?e.message:'Connection failed')}finally{setBusy('')}}
 const save=async()=>{setBusy('save');setMessage('');try{await connectProvider(token,tenantId,payload);setSecret('');setOpen(false);await load();setMessage('Provider connected and ready for gateway traffic.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to connect')}finally{setBusy('')}}
 const live=async()=>{if(!apiKey)return;setBusy('live');setMessage('');try{const r=await sendTestRequest(apiKey);setMessage(`Live request succeeded through ${r.provider}. Send it again to demonstrate a cache hit.`)}catch(e){setMessage(e instanceof Error?e.message:'Test request failed')}finally{setBusy('')}}
 return <article className='panel provider-onboarding'><div className='panel-head'><div><h2>Provider connections</h2><p>Bring your own provider key. Credentials are encrypted and isolated to this workspace.</p></div><button className='connect-button' onClick={()=>setOpen(!open)}>{open?'Cancel':'+ Connect provider'}</button></div><div className='onboarding-steps'><span className={connections.length?'done':''}><i>{connections.length?'✓':'1'}</i>Connect provider</span><span className={connections.length?'done':''}><i>2</i>Copy gateway URL</span><span><i>3</i>Send test request</span></div>{message&&<div className={message.includes('successful')||message.includes('succeeded')||message.includes('ready')?'provider-message success':'provider-message'}>{message}</div>}{open&&<div className='provider-form'><label>Provider<select value={type} onChange={e=>{setType(e.target.value);setUrl('');setModel('')}}>{presets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>API key<input type='password' value={secret} onChange={e=>setSecret(e.target.value)} placeholder='Stored encrypted — never shown again'/></label><label>Base URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder={preset?.base_url||'https://api.example.com/v1'}/></label><label>Model<input value={model} onChange={e=>setModel(e.target.value)} placeholder={preset?.model||'model-name'}/></label><div className='cost-fields'><label>Input $ / 1M tokens<input type='number' min='0' step='0.01' value={input} onChange={e=>setInput(e.target.value)}/></label><label>Output $ / 1M tokens<input type='number' min='0' step='0.01' value={output} onChange={e=>setOutput(e.target.value)}/></label></div><div className='provider-actions'><button onClick={()=>void test()} disabled={!secret||Boolean(busy)}>{busy==='test'?'Testing…':'Test connection'}</button><button onClick={()=>void save()} disabled={!secret||Boolean(busy)}>{busy==='save'?'Saving…':'Save connection'}</button></div></div>}<div className='connection-list'>{connections.map(c=><div className='connection-row' key={c.id}><i>{c.name[0]}</i><div><b>{c.name}</b><span>{c.model} · {c.base_url}</span></div><span className='connected'>● Connected</span><button onClick={async()=>{if(confirm('Remove this provider connection?')){await disconnectProvider(token,tenantId,c.id);await load()}}}>Remove</button></div>)}</div>{connections.length>0&&<div className='integration-step'><div><b>Gateway URL</b><code>{window.location.origin}/v1</code></div><button onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/v1`)}>Copy URL</button><button className='live-test' disabled={!apiKey||Boolean(busy)} onClick={()=>void live()}>{busy==='live'?'Sending…':'Send live test'}</button></div>}</article>
}
