import { useEffect, useState } from 'react'
import type { ReliabilityPolicy } from '../types'
import { fetchReliability, saveReliability } from '../lib/api'

export default function ReliabilityPanel({token,tenantId}:{token:string;tenantId:string}){
 const [policy,setPolicy]=useState<ReliabilityPolicy|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{setPolicy(null);void fetchReliability(token,tenantId).then(setPolicy).catch(e=>setMessage(e.message))},[token,tenantId])
 if(!policy)return <article className='panel reliability-panel'><h2>Reliability controls</h2><p>{message||'Loading policy…'}</p></article>
 const update=(key:keyof ReliabilityPolicy,value:number)=>setPolicy({...policy,[key]:value}),percent=policy.monthly_budget?Math.min(100,policy.spent_this_month/policy.monthly_budget*100):0
 const save=async()=>{setSaving(true);setMessage('');try{setPolicy(await saveReliability(token,tenantId,{monthly_budget:policy.monthly_budget,rate_limit_per_minute:policy.rate_limit_per_minute,max_retries:policy.max_retries,timeout_seconds:policy.timeout_seconds}));setMessage('Reliability policy saved.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save')}finally{setSaving(false)}}
 return <article className='panel reliability-panel'><div className='panel-head'><div><h2>Reliability controls</h2><p>Protect spend and define how the gateway responds to provider failures.</p></div><span className='shield-pill'>◆ Protected</span></div><div className='budget-summary'><div><span>Spent this month</span><b>${policy.spent_this_month.toFixed(2)}</b></div><div><span>Monthly budget</span><b>${policy.monthly_budget.toFixed(2)}</b></div><div><span>Remaining</span><b>${policy.remaining_budget.toFixed(2)}</b></div></div><div className='budget-track'><i style={{width:`${percent}%`}}/></div><div className='reliability-fields'><label>Monthly budget ($)<input type='number' min='0' max='1000000' value={policy.monthly_budget} onChange={e=>update('monthly_budget',Number(e.target.value))}/><small>Set 0 for no workspace budget cap.</small></label><label>Requests per minute<input type='number' min='1' max='100000' value={policy.rate_limit_per_minute} onChange={e=>update('rate_limit_per_minute',Number(e.target.value))}/><small>Excess traffic receives HTTP 429.</small></label><label>Retries per provider<select value={policy.max_retries} onChange={e=>update('max_retries',Number(e.target.value))}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select><small>Fallback starts after retries are exhausted.</small></label><label>Provider timeout (seconds)<input type='number' min='5' max='120' value={policy.timeout_seconds} onChange={e=>update('timeout_seconds',Number(e.target.value))}/><small>Applies to each provider attempt.</small></label></div>{message&&<p className='reliability-message'>{message}</p>}<div className='reliability-footer'><p>Fallback order follows your provider connection order.</p><button onClick={()=>void save()} disabled={saving}>{saving?'Saving…':'Save policy'}</button></div></article>
}
