import { useState } from 'react'
import { changePassword, exportAccount } from '../lib/api'

export default function SecurityPanel({token}:{token:string}){
 const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[exporting,setExporting]=useState(false)
 const save=async()=>{setMessage('');if(next!==confirm){setMessage('New passwords do not match.');return}if(next.length<12){setMessage('Use at least 12 characters.');return}setSaving(true);try{await changePassword(token,current,next);setCurrent('');setNext('');setConfirm('');setMessage('Password updated successfully.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to update password')}finally{setSaving(false)}}
 const download=async()=>{setExporting(true);setMessage('');try{const data=await exportAccount(token),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='promptcache-account-export.json';link.click();URL.revokeObjectURL(link.href);setMessage('Account data export downloaded.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to export account')}finally{setExporting(false)}}
 return <article className='panel security-panel'><div className='panel-head'><div><h2>Account security</h2><p>Change your password with current-password verification.</p></div><span className='shield-pill'>Protected</span></div><div className='security-fields'><label>Current password<input type='password' value={current} onChange={e=>setCurrent(e.target.value)} autoComplete='current-password'/></label><label>New password<input type='password' value={next} onChange={e=>setNext(e.target.value)} minLength={12} autoComplete='new-password'/><small>At least 12 characters.</small></label><label>Confirm new password<input type='password' value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={12} autoComplete='new-password'/></label></div>{message&&<p className='reliability-message'>{message}</p>}<div className='security-footer'><p>Current browser sessions remain valid until their normal expiry.</p><button onClick={()=>void save()} disabled={saving||!current||!next||!confirm}>{saving?'Updating…':'Update password'}</button></div><div className='data-export'><div><b>Export your data</b><p>Download your account, workspace settings, activity, and audit history. Provider secrets are never included.</p></div><button onClick={()=>void download()} disabled={exporting}>{exporting?'Preparing…':'Download JSON'}</button></div></article>
}
