import { useEffect, useState } from 'react'
import type { MemberCandidate, WorkspaceInvitation, WorkspaceMember } from '../types'
import { createWorkspaceInvitation, fetchWorkspaceInvitations, fetchWorkspaceMembers, inviteWorkspaceMember, removeWorkspaceMember, revokeWorkspaceInvitation, searchMemberCandidates, updateWorkspaceMember } from '../lib/api'

export default function TeamPanel({token,tenantId}:{token:string;tenantId:string}){
 const [members,setMembers]=useState<WorkspaceMember[]>([]),[invitations,setInvitations]=useState<WorkspaceInvitation[]>([]),[email,setEmail]=useState(''),[role,setRole]=useState<'admin'|'viewer'>('viewer'),[suggestions,setSuggestions]=useState<MemberCandidate[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{try{const [nextMembers,nextInvites]=await Promise.all([fetchWorkspaceMembers(token,tenantId),fetchWorkspaceInvitations(token,tenantId)]);setMembers(nextMembers);setInvitations(nextInvites)}catch(e){setMessage(e instanceof Error?e.message:'Unable to load team')}}
 useEffect(()=>{setMembers([]);setInvitations([]);setMessage('');void load()},[token,tenantId])
 useEffect(()=>{const query=email.trim();if(query.length<2){setSuggestions([]);return}let cancelled=false;const timer=window.setTimeout(()=>{void searchMemberCandidates(token,tenantId,query).then(users=>{if(!cancelled)setSuggestions(users)}).catch(()=>{if(!cancelled)setSuggestions([])})},250);return()=>{cancelled=true;window.clearTimeout(timer)}},[email,token,tenantId])
 const invite=async()=>{setBusy(true);setMessage('');try{await inviteWorkspaceMember(token,tenantId,email,role);setEmail('');setSuggestions([]);setMessage('Member added to the workspace.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to add member')}finally{setBusy(false)}}
 const createInvite=async()=>{setBusy(true);setMessage('');try{const invitation=await createWorkspaceInvitation(token,tenantId,email,role);const link=`${window.location.origin}/?invite=${invitation.token}`;await navigator.clipboard.writeText(link);setEmail('');setSuggestions([]);setMessage(`Invitation link copied for ${invitation.email}. It expires in 7 days.`);await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to create invitation')}finally{setBusy(false)}}
 const update=async(member:WorkspaceMember,next:'admin'|'viewer')=>{setBusy(true);try{await updateWorkspaceMember(token,tenantId,member.id,member.email,next);await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to update role')}finally{setBusy(false)}}
 const remove=async(member:WorkspaceMember)=>{if(!confirm(`Remove ${member.email} from this workspace?`))return;setBusy(true);try{await removeWorkspaceMember(token,tenantId,member.id);await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to remove member')}finally{setBusy(false)}}
 const revoke=async(invitation:WorkspaceInvitation)=>{if(!confirm(`Revoke the invitation for ${invitation.email}?`))return;setBusy(true);try{await revokeWorkspaceInvitation(token,tenantId,invitation.id);await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to revoke invitation')}finally{setBusy(false)}}
 return <article className='panel team-panel'><div className='panel-head'><div><h2>Team access</h2><p>Add registered users or invite anyone by email.</p></div><span className='team-pill'>{members.length} members</span></div><div className='team-invite'><div className='team-search'><input value={email} onChange={e=>setEmail(e.target.value)} placeholder='Email address' inputMode='email' autoComplete='off'/>{email.trim().length>=2&&<div className='team-search-results' role='listbox'>{suggestions.length?suggestions.map(user=><button type='button' key={user.id} onClick={()=>{setEmail(user.email);setSuggestions([])}}><i>{user.email[0].toUpperCase()}</i><span>{user.email}</span></button>):<p>Not registered yet? Create an invitation link.</p>}</div>}</div><select value={role} onChange={e=>setRole(e.target.value as 'admin'|'viewer')}><option value='viewer'>Viewer</option><option value='admin'>Admin</option></select><button onClick={()=>void invite()} disabled={busy||!email}>{busy?'Saving…':'Add member'}</button><button className='team-link-button' onClick={()=>void createInvite()} disabled={busy||!email}>Copy invite link</button></div><p className='team-help'>Use Add member for a matching registered account. Invite links work for anyone and can only be accepted by the invited email within 7 days.</p>{message&&<p className='reliability-message'>{message}</p>}{invitations.length>0&&<div className='team-pending'><b>Pending invitations</b>{invitations.map(invitation=><section key={invitation.id}><span>{invitation.email} · {invitation.role}</span><button disabled={busy} onClick={()=>void revoke(invitation)}>Revoke</button></section>)}</div>}<div className='team-list'>{members.map(member=><section key={member.id}><i>{member.email[0].toUpperCase()}</i><div><b>{member.email}</b><span>{member.role==='owner'?'Full workspace control':member.role==='admin'?'Operational settings access':'Read-only workspace access'}</span></div>{member.role==='owner'?<strong>Owner</strong>:<><select value={member.role} disabled={busy} onChange={e=>void update(member,e.target.value as 'admin'|'viewer')}><option value='viewer'>Viewer</option><option value='admin'>Admin</option></select><button disabled={busy} onClick={()=>void remove(member)}>Remove</button></>}</section>)}</div></article>
}
